---
version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  BeforeInstall:
  AfterInstall:
  ApplicationStart:
    - location: /home/myscript.sh
      timeout: 300
      runas: root
  ApplicationStop:
